language: android
dist: trusty
sudo: false
os: linux

android:
  components:
    - build-tools-29.0.2
    - android-29
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

git:
  depth: 10
  quiet: true

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-29"

env:
  - JOB="./gradlew clean assembleDebug"
  - JOB="./gradlew ktlint"

script: ${JOB}

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache